name: News-Dashboard
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Test app News-Dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test

  